### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by spuder** [Appdynamics/appdynamics-cookbooks#76]
Getting these deprecation warnings

- Ubuntu 16.04
- Java agent

```
Deprecated features used!
  The on_platforms option to node_map has been deprecated at 1 location:
    - /var/chef/cache/cookbooks/powershell/libraries/powershell_module_resource.rb:25:in `<class:PowershellModule>'
   See https://docs.chef.io/deprecations_internal_api.html for further details.
  method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at 3 locations:
    - /var/chef/cache/cookbooks/python/attributes/default.rb:23:in `from_file'
    - /var/chef/cache/cookbooks/python/attributes/default.rb:24:in `from_file'
    - /var/chef/cache/cookbooks/python/attributes/default.rb:39:in `from_file'
   See https://docs.chef.io/deprecations_attributes.html for further details.
```

**Comment by hamBank** [comment]
This (among other issues) now causes this cookbook to be unusable with chef14.

**Comment by spuder** [comment]
This cookbook is abandoned. Many of the design patterns are also out of date. It’s far easier to write your own cookbook that manages the packages and config files.

**Comment by hamBank** [comment]
I guess my point was that if appD isn't going to actually come out and say so they should be supporting their code.. I'd agree that there is quite a lot in here that's out of date..
